### ISSUE TITLE
Missing and bad modules on attempt to run in Linux environment

### ISSUE THREAD

**Issue by Camtendo** [dguenther/web-overlay#49]
EDIT: Being investigated

When trying to run in Linux, there were problems with the following modules. Note that we could probably resolve these by adding them to the `package.json`
+ debug - Missing
+ express - Nonexistent target version (highest is 3.X)

**Comment by dguenther** [comment]
Do you have an environment I can debug in? I thought both of those were in
package.json already.

**Comment by Camtendo** [comment]
I'm gonna keep looking into it. I think that Ubuntu's official Node version (via `apt-get`) was just garbage. Give me a day on this.

**Comment by dguenther** [comment]
Ah, I'd believe it. An old version of node would make sense.

**Comment by Camtendo** [comment]
Yeah, for whatever reason, node didn't acknowledge `package.json`. We livin' now though.
