### ISSUE TITLE
Add a "we'll be right back" page to the web overlay

### ISSUE THREAD

**Issue by dguenther** [dguenther/web-overlay#51]
We're doing this offline right now, but I think it would be nice to have in the web overlay at some point in case we want to put some cool stuff on it. One example would be results from earlier tournaments that day. Another thing I saw Capcom do on a stream that was pretty neat was a rotation of random Street Fighter facts. We could do something similar for Smash.

**Comment by Camtendo** [comment]
This is brilliant. I'll look for some Smash facts I can scrape and get something made.

**Comment by dguenther** [comment]
Sweet. Think they should be game specific and/or include eSports facts?

**Comment by Camtendo** [comment]
We could add a tool to choose from different genres of facts that we put in a JSON file somewhere.

**Comment by Camtendo** [comment]
The base image is here: https://imgur.com/SkOH3j1

**Comment by dguenther** [comment]
Yo, this looks sweet. It'd be cool to animate the text in character by character and have the cursor blink or something.

**Comment by Camtendo** [comment]
I'll look into that this weekend. :+1:

**Comment by Camtendo** [comment]
I found a way to do it without jQuery: http://www.paulund.co.uk/playground/demo/typing-effect/

**Comment by dguenther** [comment]
Oh the CSS animation? Man whatever works would be cool haha

**Comment by Camtendo** [comment]
CSS prevents word-wrapping, so I'm using JS instead.

**Comment by dguenther** [comment]
Isn't there a property for that? Well whatever works is okay with me. I'll
check it out when it's PRd too

**Comment by Camtendo** [comment]
I tried everything, and nothing worked. With pure CSS. It works great for one-liners though.

**Comment by Camtendo** [comment]
Will be fixed with https://github.com/dguenther/web-overlay/pull/56
