### ISSUE TITLE
Add ability to hide commentator name element in admin

### ISSUE THREAD

**Issue by Camtendo** [dguenther/web-overlay#54]
We should be able to hide or show that image+text, as well as animate it.

**Comment by dguenther** [comment]
Like make the whole image disappear? What were your thoughts on how this would be used?

**Comment by Camtendo** [comment]
I was thinking of using it as a stopgap until we can trigger animations after OBS scene change. So we'd switch to the scene and only animate the names in once I ensured they were updated.

**Comment by Camtendo** [comment]
We can achieve this effect in OBS by having 2 separate views for commentators. The names can fade in. Closing.
