### ISSUE TITLE
Trent Feedback

### ISSUE THREAD

**Issue by Camtendo** [dguenther/web-overlay#55]
Pardon the Smash
==================
Remove my camera
Use Derek's computer
Noah is BANNED
Check footage beforehand
Better handle viewport
Find better way to communicate to talkers
Make an actual layout for viewport
More videos for each topic/Don't replay videos
Make video under 1:00:00
Implement Veto System?
Better ending
Interact with chat
Images are acceptable
Have bonus/guest topic at halfway point

Web-Overlay
===================
Twitter Handle section
Have ReesayBot use the bracket from Admin

**Comment by dguenther** [comment]
We should split this out into separate issues and put the non-web-overlay related stuff in a google doc or something.

**Comment by Camtendo** [comment]
Will do. I just wanted to quickly get this somewhere.

**Comment by Camtendo** [comment]
PtS is on hiatus (most of this stuff was implemented anyway).
