### ISSUE TITLE
Create a "Ready/Not Ready" view for players

### ISSUE THREAD

**Issue by Camtendo** [dguenther/web-overlay#72]
This screen will be incredibly useful. The thought is, we'll have a ready button in the `admin.hbs` view that we can toggle when all stream information is up-to-date. We'll then have a cheap tablet/computer (currently thinking my Chromebook) next to the console that the players are using. We'll show a red screen saying "NOT READY" when not ready, and a green screen saying "READY".

This should eliminate the need to yell at players to wait for the stream.

**Comment by dguenther** [comment]
I really like this. Nice.
