### ISSUE TITLE
Scale overlay fonts based on content

### ISSUE THREAD

**Issue by dguenther** [dguenther/web-overlay#9]
Right now, player text wraps off the bottom of the overlay using `overflow-wrap: break-word`. It'd be nice to scale player text down based on how long the text is. So for long team names, the text would be smaller, but for short single player names, the text would be regular size. As far as I know, this needs javascript to implement.

**Comment by Camtendo** [comment]
This is no longer a problem for the new 16by9 layout (supports like 60 characters or something). It will be applied to the 4by3 layout though.

**Comment by Camtendo** [comment]
Should be implemented in https://github.com/dguenther/web-overlay/pull/62
